src/task_dashboard/__init__.py
__version__ = "0.1b1"

src/task_dashboard/blueprints/__init__.py
from .tasks import bp as tasks_bp  # noqa

src/task_dashboard/blueprints/tasks.py
from typing import Optional

from flask import Blueprint, abort, current_app, render_template
from task_logs.backends.backend import EnqueuedLog

bp = Blueprint("tasks", __name__, url_prefix="/tasks")


@bp.route("/")
def list() -> str:
    logs = current_app.task_logs_backend.all()
    return render_template("tasks/list.html", logs=logs)


@bp.route("/<string:task_id>/")
def show(task_id: str) -> str:
    logs = current_app.task_logs_backend.find_task(task_id)
    enqueued_log: Optional[EnqueuedLog] = None
    if not logs:
        abort(404)

    last_log = logs[0]
    if logs[-1]["type"] == "enqueued":
        enqueued_log = logs[-1]

    return render_template(
        "tasks/show.html", logs=logs, enqueued_log=enqueued_log, last_log=last_log
    )

src/task_dashboard/task_backends/__init__.py
from pydoc import locate
from typing import Any

from task_logs.backends.backend import ReaderBackend


def load_task_logs_backend(class_fqn: str, options: Any) -> ReaderBackend:
    backend_cls: Any = locate(class_fqn)

    if isinstance(backend_cls, ReaderBackend):
        return backend_cls  # pragma: no cover

    if not issubclass(backend_cls, ReaderBackend):
        raise ValueError(
            f"{backend_cls} is not a ReaderBackend class"
        )  # pragma: no cover

    return backend_cls(**options)

src/task_dashboard/task_backends/controller.py
import abc
from typing import Any, Dict, List


class BaseController(abc.ABC):
    @abc.abstractproperty
    def name(self) -> str:
        raise NotImplementedError

    @abc.abstractmethod
    def enqueue_task(
        self,
        name: str,
        args: List[Any],
        kwargs: Dict[str, Any],
        options: Dict[str, Any],
    ) -> str:
        raise NotImplementedError

src/task_dashboard/templates/index.html
{% extends 'layout.html' %}

Hello.

src/task_dashboard/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tasks Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <link rel="stylesheet" href="/static/style.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
    <nav class="navbar header" role="navigation" aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <h3>Tasks Dasboard</h3>
          </a>

          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar-menu">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbar-menu" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="{{ url_for('tasks.list') }}">
              Tasks
            </a>
          </div>
        </div>
      </div>
    </nav>


    {% with messages = get_flashed_messages() %}
      {% if messages %}
      <section class="section">
        <div class="container">
          <ul>
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
          </ul>
        </div>
      </section>
      {% endif %}
    {% endwith %}

    <section class="section">
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </section>
  </body>
</html>

src/task_dashboard/templates/tasks/list.html
{% extends 'layout.html' %}

{% block content %}
  <h2 class="title is-2">Tasks</h2>
  <table class="table is-fullwidth is-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th class"is-1"><abbr title="Task Identifier">Id</abbr></th>
        <th>Date</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
      {% for log in logs %}
        <tr>
          <td>{{ log.task_name }}</td>
          <td><a href="{{ url_for('tasks.show', task_id=log.task_id) }}">{{ log.task_id }}</a></td>
          <td>{{ log.timestamp }}</td>
          <td>{{ log.type | titlize }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

src/task_dashboard/templates/tasks/show.html
{% extends 'layout.html' %}

{% block content %}
  <h2 class="title is-2">Task <span class="identifier">{{ last_log.task_name }}</span></h2>
  <h6 class="subtitle is-6">{{ enqueued_log | repr_task }}</h6>
  <div class="panel">
    <p class="panel-heading">
      Details
    </p>
    <div class="panel-block">
      <dl>
        <dt>Id</dt>
        <dd>{{ last_log.task_id }}</dd>
        <dt>Enqueued at</dt>
        <dd>{{ enqueued_log.timestamp }}</dd>
      </dl>
    </div>
  </div>
  <div class="panel">
    <p class="panel-heading">
      Events
    </p>
    <div class="panel-block">
      <table class="table is-fullwidth is-striped">
        <thead>
          <tr>
            <th>Type</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          {% for log in logs %}
            <tr>
              <td>{{ log.type | titlize }}</td>
              <td>{{ log.timestamp }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="panel">
    <p class="panel-heading">
      Data
    </p>
    <div class="panel-block">
      <pre style="width: 100%">{{ logs | pprint }}</pre>
    </div>
  </div>
{% endblock %}